apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: k3d-microservice
servers: 1
agents: 2
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik@server:0
        nodeFilters:
          - server:*